# Generated by Django 3.0 on 2020-01-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=20)),
                ('abbrev', models.CharField(max_length=20)),
                ('group', models.CharField(default='', max_length=2)),
                ('captain1', models.CharField(max_length=30)),
                ('captain2', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
