# Generated by Django 3.0 on 2020-01-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0002_playerunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerunit',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
