# Generated by Django 3.0 on 2020-01-26 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0003_auto_20200125_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('umpire1', models.CharField(default='', max_length=50)),
                ('umpire2', models.CharField(default='', max_length=50)),
                ('umpire3', models.CharField(default='', max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('ps', models.CharField(default='', max_length=100)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlapp.TeamUnit')),
            ],
        ),
    ]
