# Generated by Django 3.0 on 2020-01-26 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0004_gameunit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameUnit',
        ),
    ]
