# Generated by Django 3.0 on 2020-01-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0005_delete_gameunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=30)),
                ('guest', models.CharField(max_length=50)),
                ('home', models.CharField(max_length=50)),
                ('umpire1', models.CharField(default='', max_length=50)),
                ('umpire2', models.CharField(default='', max_length=50)),
                ('umpire3', models.CharField(default='', max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('ps', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
