# Generated by Django 3.0 on 2020-01-30 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0006_gameunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameunit',
            name='guestScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameunit',
            name='homeScore',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ScoreUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest1', models.IntegerField(default=0)),
                ('guest2', models.IntegerField(default=0)),
                ('guest3', models.IntegerField(default=0)),
                ('guest4', models.IntegerField(default=0)),
                ('guest5', models.IntegerField(default=0)),
                ('guest6', models.IntegerField(default=0)),
                ('guest7', models.IntegerField(default=0)),
                ('home1', models.IntegerField(default=0)),
                ('home2', models.IntegerField(default=0)),
                ('home3', models.IntegerField(default=0)),
                ('home4', models.IntegerField(default=0)),
                ('home5', models.IntegerField(default=0)),
                ('home6', models.IntegerField(default=0)),
                ('home7', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlapp.GameUnit')),
            ],
        ),
    ]
