# Generated by Django 3.0 on 2020-02-01 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0008_hitterunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitcherUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conseq', models.CharField(max_length=10)),
                ('inn_int', models.IntegerField(default=0)),
                ('inn_float', models.IntegerField(default=0)),
                ('TPAF', models.IntegerField(default=0)),
                ('TBF', models.IntegerField(default=0)),
                ('P', models.IntegerField(default=0)),
                ('CG', models.CharField(max_length=50)),
                ('SHO', models.CharField(max_length=50)),
                ('no_walks', models.CharField(max_length=50)),
                ('H', models.IntegerField(default=0)),
                ('HR', models.IntegerField(default=0)),
                ('SH', models.IntegerField(default=0)),
                ('SF', models.IntegerField(default=0)),
                ('BB', models.IntegerField(default=0)),
                ('IBB', models.IntegerField(default=0)),
                ('DB', models.IntegerField(default=0)),
                ('K', models.IntegerField(default=0)),
                ('WP', models.IntegerField(default=0)),
                ('BK', models.IntegerField(default=0)),
                ('R', models.IntegerField(default=0)),
                ('ER', models.IntegerField(default=0)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlapp.GameUnit')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlapp.PlayerUnit')),
            ],
        ),
    ]
