# Generated by Django 3.0 on 2020-02-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0009_pitcherunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitcherunit',
            name='conseq',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='FielderUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=50)),
                ('PO', models.IntegerField(default=0)),
                ('A', models.IntegerField(default=0)),
                ('E', models.IntegerField(default=0)),
                ('DP', models.IntegerField(default=0)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlapp.GameUnit')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlapp.PlayerUnit')),
            ],
        ),
    ]
