# Generated by Django 3.0 on 2020-02-01 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0010_auto_20200201_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatcherUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PB', models.IntegerField(default=0)),
                ('interference', models.IntegerField(default=0)),
                ('stolen', models.IntegerField(default=0)),
                ('CS', models.IntegerField(default=0)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlapp.GameUnit')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlapp.PlayerUnit')),
            ],
        ),
    ]
