# Generated by Django 3.0 on 2020-02-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0011_catcherunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameunit',
            name='date',
            field=models.DateField(),
        ),
    ]
