# Generated by Django 3.0 on 2020-02-04 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0013_auto_20200203_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerHitterUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PA', models.IntegerField(default=0)),
                ('AB', models.IntegerField(default=0)),
                ('RBI', models.IntegerField(default=0)),
                ('R', models.IntegerField(default=0)),
                ('H', models.IntegerField(default=0)),
                ('TwoBH', models.IntegerField(default=0)),
                ('ThreeBH', models.IntegerField(default=0)),
                ('HR', models.IntegerField(default=0)),
                ('TB', models.IntegerField(default=0)),
                ('DP', models.IntegerField(default=0)),
                ('SH', models.IntegerField(default=0)),
                ('SF', models.IntegerField(default=0)),
                ('Walks', models.IntegerField(default=0)),
                ('SO', models.IntegerField(default=0)),
                ('SB', models.IntegerField(default=0)),
                ('CS', models.IntegerField(default=0)),
                ('LOB', models.IntegerField(default=0)),
                ('AVG', models.FloatField(null=True)),
                ('OBP', models.FloatField(null=True)),
                ('SLG', models.FloatField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlapp.PlayerUnit')),
            ],
        ),
    ]
