# Generated by Django 3.0 on 2020-02-04 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0014_playerhitterunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCatcherUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PB', models.IntegerField(default=0)),
                ('interference', models.IntegerField(default=0)),
                ('stolen', models.IntegerField(default=0)),
                ('CS', models.IntegerField(default=0)),
                ('CSP', models.FloatField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlapp.PlayerUnit')),
            ],
        ),
    ]
