# Generated by Django 3.0 on 2020-02-04 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0016_playerfielderunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPitcherUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W', models.IntegerField(default=0)),
                ('L', models.IntegerField(default=0)),
                ('S', models.IntegerField(default=0)),
                ('BS', models.IntegerField(default=0)),
                ('inn3', models.IntegerField(default=0)),
                ('TPAF', models.IntegerField(default=0)),
                ('TBF', models.IntegerField(default=0)),
                ('P', models.IntegerField(default=0)),
                ('CG', models.IntegerField(default=0)),
                ('SHO', models.IntegerField(default=0)),
                ('no_walks', models.IntegerField(default=0)),
                ('H', models.IntegerField(default=0)),
                ('HR', models.IntegerField(default=0)),
                ('SH', models.IntegerField(default=0)),
                ('SF', models.IntegerField(default=0)),
                ('BB', models.IntegerField(default=0)),
                ('IBB', models.IntegerField(default=0)),
                ('DB', models.IntegerField(default=0)),
                ('K', models.IntegerField(default=0)),
                ('WP', models.IntegerField(default=0)),
                ('BK', models.IntegerField(default=0)),
                ('R', models.IntegerField(default=0)),
                ('ER', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlapp.PlayerUnit')),
            ],
        ),
    ]
