# Generated by Django 3.0 on 2020-02-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0017_playerpitcherunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpitcherunit',
            name='AVG',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='playerpitcherunit',
            name='ERA',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='playerpitcherunit',
            name='OBA',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='playerpitcherunit',
            name='WHIP',
            field=models.FloatField(null=True),
        ),
    ]
