# Generated by Django 3.0 on 2020-02-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0019_auto_20200205_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamunit',
            name='abbrev',
        ),
    ]
