# Generated by Django 3.0 on 2020-02-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0020_remove_teamunit_abbrev'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameunit',
            name='playoff',
            field=models.BooleanField(default=False),
        ),
    ]
