# Generated by Django 3.0 on 2020-02-13 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0022_playerpitcherunit_ho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameunit',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='controlapp.TeamUnit'),
        ),
        migrations.AlterField(
            model_name='gameunit',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='controlapp.TeamUnit'),
        ),
    ]
