# Generated by Django 3.0 on 2020-02-14 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0023_auto_20200213_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHomeUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('second', models.CharField(max_length=100)),
                ('third', models.CharField(max_length=100)),
                ('fourth', models.CharField(max_length=100)),
                ('fifth', models.CharField(max_length=100)),
                ('sixth', models.CharField(max_length=100)),
                ('seventh', models.CharField(max_length=100)),
                ('eighth', models.CharField(max_length=100)),
                ('nineth', models.CharField(max_length=100)),
                ('SP', models.CharField(max_length=100)),
                ('substitute1', models.CharField(max_length=100)),
                ('substitute2', models.CharField(max_length=100)),
                ('substitute3', models.CharField(max_length=100)),
                ('substitute4', models.CharField(max_length=100)),
                ('substitute5', models.CharField(max_length=100)),
                ('substitute6', models.CharField(max_length=100)),
                ('substitute7', models.CharField(max_length=100)),
                ('substitute8', models.CharField(max_length=100)),
                ('substitute9', models.CharField(max_length=100)),
                ('submitTime', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlapp.GameUnit')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGuestUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('second', models.CharField(max_length=100)),
                ('third', models.CharField(max_length=100)),
                ('fourth', models.CharField(max_length=100)),
                ('fifth', models.CharField(max_length=100)),
                ('sixth', models.CharField(max_length=100)),
                ('seventh', models.CharField(max_length=100)),
                ('eighth', models.CharField(max_length=100)),
                ('nineth', models.CharField(max_length=100)),
                ('SP', models.CharField(max_length=100)),
                ('substitute1', models.CharField(max_length=100)),
                ('substitute2', models.CharField(max_length=100)),
                ('substitute3', models.CharField(max_length=100)),
                ('substitute4', models.CharField(max_length=100)),
                ('substitute5', models.CharField(max_length=100)),
                ('substitute6', models.CharField(max_length=100)),
                ('substitute7', models.CharField(max_length=100)),
                ('substitute8', models.CharField(max_length=100)),
                ('substitute9', models.CharField(max_length=100)),
                ('submitTime', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlapp.GameUnit')),
            ],
        ),
    ]
