# Generated by Django 3.0 on 2020-02-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0025_auto_20200214_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhomeunit',
            name='substitute1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderhomeunit',
            name='substitute2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderhomeunit',
            name='substitute3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderhomeunit',
            name='substitute4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderhomeunit',
            name='substitute5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderhomeunit',
            name='substitute6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderhomeunit',
            name='substitute7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderhomeunit',
            name='substitute8',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderhomeunit',
            name='substitute9',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
