# Generated by Django 3.0 on 2020-02-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0026_auto_20200215_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('eventVote', models.BooleanField(default=False)),
            ],
        ),
    ]
