# Generated by Django 3.0 on 2020-02-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0027_eventunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('votes', models.IntegerField(default=0)),
                ('percent', models.FloatField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlapp.EventUnit')),
            ],
        ),
        migrations.CreateModel(
            name='VoterUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('randomkey', models.CharField(max_length=50)),
                ('confirm', models.BooleanField(default=False)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlapp.OptionUnit')),
            ],
        ),
    ]
