# Generated by Django 3.0 on 2020-03-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0029_auto_20200307_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventunit',
            name='eventChoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventunit',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
