# Generated by Django 3.0 on 2020-03-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0030_auto_20200307_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameunit',
            name='album',
            field=models.CharField(default='', max_length=200),
        ),
    ]
