# Generated by Django 3.0.8 on 2020-07-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0032_auto_20200704_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerunit',
            name='year',
        ),
    ]
