# Generated by Django 3.0.8 on 2020-07-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0033_remove_playerunit_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerunit',
            name='umpire',
            field=models.BooleanField(default=False),
        ),
    ]
