# Generated by Django 3.0.8 on 2020-07-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0034_playerunit_umpire'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('studentID', models.CharField(max_length=20)),
            ],
        ),
    ]
