# Generated by Django 3.0.8 on 2020-07-09 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0035_personunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerunit',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controlapp.PlayerUnit'),
        ),
    ]
