# Generated by Django 3.0.8 on 2020-07-09 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0036_playerunit_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerunit',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controlapp.PersonUnit'),
        ),
    ]
