# Generated by Django 3.0.8 on 2020-07-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0037_auto_20200709_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerunit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='playerunit',
            name='studentID',
        ),
    ]
