# Generated by Django 3.0.8 on 2020-07-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0038_auto_20200709_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamunit',
            name='year',
            field=models.IntegerField(),
        ),
    ]
