# Generated by Django 3.0.8 on 2020-07-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0039_auto_20200709_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameunit',
            name='year',
            field=models.IntegerField(),
        ),
    ]
