# Generated by Django 3.0.8 on 2020-07-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0040_auto_20200709_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalID', models.CharField(max_length=20)),
                ('newID', models.CharField(max_length=20)),
            ],
        ),
    ]
