# Generated by Django 3.0.8 on 2020-08-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0041_transferunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameunit',
            name='allstar',
            field=models.BooleanField(default=False),
        ),
    ]
