# Generated by Django 3.1.2 on 2021-03-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0042_gameunit_allstar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitcherunit',
            name='conseq',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
