# Generated by Django 3.1.9 on 2021-11-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0043_auto_20210316_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamunit',
            name='T',
            field=models.IntegerField(default=0),
        ),
    ]
